#  docker-compose -p postgres-local -f docker-compose.yml up -d

services:

  postgres-keycloak:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    container_name: postgres-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "8080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_PASSWORD=password
    container_name: keycloak